### ISSUE TITLE
Other Android Distribution Wanted

### ISSUE THREAD

**Issue by swety2003** [pissarro-dev/device_xiaomi_pissarro#2]
Hey, I'm glad this device can flash third-party ROM and thats really a good job.But I prefer a more customized system.
Therefore I tried to build EvolutionX using this device tree, and successfully got system.img and product.img, but when I install them with dsu sideloader, I found that it even could not enter the second screen and entered recovery.
I don't think I can solve this problem with my poor knowledge, so I want to know whether this project will adopt other distributions or give me some help.

The following are some repos I used to build.

[https://github.com/pissarro-dev/device_xiaomi_pissarro](https://github.com/pissarro-dev/device_xiaomi_pissarro)
[https://github.com/pissarro-dev/vendor_xiaomi_pissarro](https://github.com/pissarro-dev/vendor_xiaomi_pissarro)
https://github.com/Evolution-X/manifest -b udc
https://github.com/AOSP-14-RMX2020/android_device_mediatek_sepolicy_vndr

build variant: lineage-pissarro-user

**Comment by rio004** [comment]
Stop using DSU sideloader and flash the ROM the intended way.

And if you don't know how to build get help.

Use the following repos:
https://github.com/pissarro-dev/device_xiaomi_pissarro
https://github.com/pissarro-dev/vendor_xiaomi_pissarro
https://github.com/PQEnablers-Devices/android_device_mediatek_sepolicy_vndr
https://github.com/PQEnablers-Devices/android_hardware_mediatek
